---
- name: Installs nginx web server
  yum: name=nginx state=latest

- name: Enable nginx service
  service: name=nginx enabled=yes

- name: nginx.conf deploy
  template: src='/../files/nginx.conf.j2' dest='/etc/nginx/nginx.conf' owner=root group=root mode=0644

- name: laravel.conf deploy
  template: src='/../files/laravel.conf' dest='/etc/nginx/conf.d/laravel.conf' owner=root group=root mode=0644

- name: Creates directory (/srv/web/www)
  file: path=/srv/web/www/laravel state=directory owner=nginx group=nginx recurse=yes

- name: Creates directory (/srv/web/www)
  file: path=/srv/web/www/utils state=directory owner=nginx group=nginx recurse=yes

- name: Creates directory (/srv/web/www)
  file: path=/srv/web/www/native state=directory owner=nginx group=nginx recurse=yes

- name: Creates directory (/srv/web/hosts)
  file: path=/srv/web/vhost state=directory owner=root group=root recurse=yes

- name: Creates directory (/srv/web/log)
  file: path=/srv/web/log state=directory owner=nginx group=nginx recurse=yes
