---
- name: Downloading EPEL repository
  action: shell echo "y"| command yum install epel-release

- name: Downloading and enable the REMI repository definitions
  action: command rpm -Uvh --replacepkgs http://remi.mirrors.arminco.com/enterprise/7/remi/x86_64/remi-release-7.1-2.el7.remi.noarch.rpm

- name: Enable REMI repository
  action: command yum-config-manager --enable remi

- name: Enable REMI-PHP55
  action: command yum-config-manager --enable remi-php56